"""feat: users.language not null

Revision ID: 66f3207c378a
Revises: f1b7b81ffe76
Create Date: 2024-05-09 19:20:10.762510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "66f3207c378a"
down_revision: Union[str, None] = "f1b7b81ffe76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "language", existing_type=sa.VARCHAR(length=2), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "language", existing_type=sa.VARCHAR(length=2), nullable=True
    )
    # ### end Alembic commands ###
